### ISSUE TITLE
enhancement: leverage encryption without keyring

### ISSUE THREAD

**Issue by erikwestlund** [table1/framework#8]
# Security Enhancement Plan: Optional Encryption for Credentials

## Overview
Currently, the framework stores credentials in memory as plaintext (loaded from .env). While this is an improvement over storing credentials in files, we can add optional encryption for environments that support it.

### 1. Update `config_skeleton.yml`
```yaml
options:
  # ... existing options ...
  security:
    use_encryption: false  # Default to false for compatibility
    encryption_key: null   # Can be set to a key file path or env var name

security:
  data_key: null
  results_key: null
  # Add encrypted versions
  encrypted_data_key: null
  encrypted_results_key: null
```

### 2. Create `security.R` with encryption utilities
```r
#' @keywords internal
has_encryption <- function() {
  requireNamespace("sodium", quietly = TRUE)
}

#' @keywords internal
encrypt_value <- function(value, key) {
  if (!has_encryption()) {
    return(value)
  }
  
  # Convert key to raw if it's a string
  if (is.character(key)) {
    key <- sodium::hex2bin(key)
  }
  
  # Encrypt
  nonce <- sodium::random(24)
  cipher <- sodium::auth_encrypt(
    charToRaw(value),
    key,
    nonce
  )
  
  # Return as hex string
  paste0(
    sodium::bin2hex(nonce),
    ":",
    sodium::bin2hex(cipher)
  )
}

#' @keywords internal
decrypt_value <- function(encrypted, key) {
  if (!has_encryption()) {
    return(encrypted)
  }
  
  # Split nonce and cipher
  parts <- strsplit(encrypted, ":")[[1]]
  if (length(parts) != 2) {
    return(encrypted)  # Not encrypted, return as is
  }
  
  # Convert key to raw if it's a string
  if (is.character(key)) {
    key <- sodium::hex2bin(key)
  }
  
  # Decrypt
  nonce <- sodium::hex2bin(parts[1])
  cipher <- sodium::hex2bin(parts[2])
  
  rawToChar(sodium::auth_decrypt(cipher, key, nonce))
}

#' @keywords internal
get_encryption_key <- function(config) {
  if (!config$options$security$use_encryption) {
    return(NULL)
  }
  
  key_source <- config$options$security$encryption_key
  if (is.null(key_source)) {
    return(NULL)
  }
  
  # If it's an env var name
  if (grepl("^env\\(.*\\)$", key_source)) {
    key <- eval_env(key_source)
  } else {
    # Assume it's a file path
    if (file.exists(key_source)) {
      key <- readLines(key_source, warn = FALSE)[1]
    } else {
      return(NULL)
    }
  }
  
  key
}

#' @keywords internal
process_encrypted_values <- function(config) {
  if (!config$options$security$use_encryption) {
    return(config)
  }
  
  key <- get_encryption_key(config)
  if (is.null(key)) {
    return(config)
  }
  
  # Process each encrypted value
  if (!is.null(config$security$encrypted_data_key)) {
    config$security$data_key <- decrypt_value(
      config$security$encrypted_data_key,
      key
    )
  }
  
  if (!is.null(config$security$encrypted_results_key)) {
    config$security$results_key <- decrypt_value(
      config$security$encrypted_results_key,
      key
    )
  }
  
  config
}
```

### 3. Modify `config.R`
Add to `read_config()` after merging with skeleton:
```r
  # After merging with skeleton
  config <- merge_with_skeleton(user_config, skeleton)
  
  # Process settings files and evaluate env() calls
  config <- process_settings(config)
  config <- eval_env(config)
  
  # Process encrypted values if encryption is enabled
  config <- process_encrypted_values(config)
```

### 1. Plaintext (default)
```yaml
security:
  data_key: "my-secret-key"
```

### 2. Encrypted
```yaml
options:
  security:
    use_encryption: true
    encryption_key: "env(ENCRYPTION_KEY)"  # or path to key file

security:
  encrypted_data_key: "encrypted-value-here"
```

## Benefits
1. Defaults to plaintext for maximum compatibility
2. Allows enabling encryption via config
3. Supports getting encryption key from:
   - Environment variable
   - File
   - Direct value
4. Gracefully falls back to plaintext if:
   - Encryption is disabled
   - `sodium` package isn't available
   - Key isn't available
5. Keeps encrypted values separate from plaintext ones
6. Makes it easy to switch between methods

## Dependencies
- `sodium` package (optional, for encryption)
- No changes to existing functionality
- No breaking changes to config structure

## Notes
- We already have some encryption utilities in `data_encrypt.R` that we can leverage
- This implementation maintains backward compatibility
- Users can gradually migrate to encryption as needed
